INSERT INTO sectors (sector_name, sector_descript)
VALUES ('Embryologist, clinical', 'Religious along agreement evidence hard.'),
 ('Scientist, research (maths)', 'Man describe fact develop purpose visit lead. Meeting perhaps item east.'),
 ('Nurse, learning disability', 'Way capital in visit book time family. Identify send see modern.'),
 ('Estate agent', 'Head evening nation operation eight. Join yes deal lot our approach toward.'),
 ('Podiatrist', 'Information door interest sell main. Respond sign man shake into sort.'),
 ('Scientist, clinical (histocompatibility and immunogenetics)', 'Score sea former deal system major. Check show discover activity.'),
 ('Conservation officer, nature', 'Record ago owner almost recognize girl sure. East part ask admit region.'),
 ('Research scientist (physical sciences)', 'Soon where official list onto especially fish. Or sell place heart record rock very.'),
 ('Medical illustrator', 'Painting prepare meeting population note.'),
 ('Scientist, research (life sciences)', 'Capital space she go. Walk business along rule financial budget small more.'),
 ('Public relations account executive', 'Expert article poor put effect far though. Back for remember believe.'),
 ('Volunteer coordinator', 'Attention get modern purpose. Pull behavior with oil manager.'),
 ('Copy', 'Idea lay long bank. Miss nice big later.'),
 ('Amenity horticulturist', 'Director wife set explain.'),
 ('Education officer, museum', 'Audience admit particularly child perform make.'),
 ('Charity fundraiser', 'Ten president election.'),
 ('Fast food restaurant manager', 'Leader political foreign war clear pressure.'),
 ('Bookseller', 'Image spring gun town.'),
 ('Food technologist', 'Task here tell list itself. With admit collection great no.'),
 ('Pensions consultant', 'Discover note charge class thank marriage bring science.');