INSERT INTO parameters (parameter_name, measure_id)
VALUES ('view', '10'),
 ('always', '3'),
 ('candidate', '13'),
 ('design', '8'),
 ('impact', '14'),
 ('management', '18'),
 ('good', '13'),
 ('never', '11'),
 ('take', '8'),
 ('beautiful', '18'),
 ('protect', '20'),
 ('way', '20'),
 ('produce', '17'),
 ('key', '9'),
 ('write', '2'),
 ('executive', '16'),
 ('until', '14'),
 ('unit', '7'),
 ('should', '18'),
 ('feel', '9');