INSERT INTO regions (region_name, region_descript)
VALUES ('Bulgaria', 'Such price fact begin human father.'),
 ('Poland', 'Dream science region start blue.'),
 ('Congo', 'Sell dream recognize away produce.'),
 ('Tokelau', 'Check but production in without many model institution. His market west police however.'),
 ('Argentina', 'Account do talk skin.'),
 ('Nauru', 'Suddenly camera leader shoulder across one. Clear turn professor upon another investment.'),
 ('Haiti', 'Student fire especially court sure full involve. Reality particularly president rich religious style.'),
 ('Maldives', 'Director the color stuff. Response address she it statement.'),
 ('Japan', 'Cut free management participant discussion cold choice enter. Light need structure east example speak.'),
 ('Mali', 'Professional social rock sure culture official tree yard.'),
 ('Portugal', 'Difference want good material vote cause allow smile. Place state successful focus think.'),
 ('Yemen', 'Hand medical season believe determine. Analysis run person project idea.'),
 ('Madagascar', 'Final build factor on.'),
 ('Saint Kitts and Nevis', 'City assume many gas. Water myself necessary situation.'),
 ('Cuba', 'Area bill focus its discussion professor fact. Size group tonight pull.'),
 ('Poland', 'Community south summer thank public hotel address. Manager economy force.'),
 ('Sri Lanka', 'World set include ever.'),
 ('French Guiana', 'City write money seem say later affect. Production citizen upon great.'),
 ('Mayotte', 'Important security could way feeling employee structure.'),
 ('Bahrain', 'Thousand eye space hold city.');